services:
  db:
    image: pgvector/pgvector:pg16
    container_name: itb_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: itb
      POSTGRES_PASSWORD: itb
      POSTGRES_DB: itb_db
      # POSTGRES_HOST_AUTH_METHOD: md5
      # POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=trust"
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./docker/02_porto_schema.sql:/docker-entrypoint-initdb.d/02_porto_schema.sql
      - ./docker/03_wisudawan_schema.sql:/docker-entrypoint-initdb.d/03_wisudawan_schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U itb -d itb_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata: