---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	query_rewriter(query_rewriter)
	planner(planner)
	step_executor(step_executor)
	sql_pipeline(sql_pipeline)
	rag_retriever(rag_retriever)
	step_reasoner(step_reasoner)
	synthesizer(synthesizer)
	clarification_handler(clarification_handler)
	__end__([<p>__end__</p>]):::last
	__start__ --> query_rewriter;
	planner -.-> clarification_handler;
	planner -.-> step_executor;
	query_rewriter --> planner;
	rag_retriever --> step_reasoner;
	sql_pipeline -.-> step_reasoner;
	sql_pipeline -.-> synthesizer;
	step_executor -.-> rag_retriever;
	step_executor -.-> sql_pipeline;
	step_executor -.-> synthesizer;
	step_reasoner -.-> step_executor;
	step_reasoner -.-> synthesizer;
	clarification_handler --> __end__;
	synthesizer --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
